/* SIGN IN */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGIN_REQUEST = "LOGIN_REQUEST"

/* USER PROFILE */

export const GET_USERPROFILE = "GET_USERPROFILE"
export const EDIT_USERNAME = "EDIT_USERNAME"
export const USERPROFILE_REQUEST = "USERPROFILE_REQUEST"
export const USERNAME_EDIT_REQUEST = "USERNAME_EDIT_REQUEST"